//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountBase()
        {
            this.AccountBase1 = new HashSet<AccountBase>();
            this.AccountBase11 = new HashSet<AccountBase>();
            this.LeadBases = new HashSet<LeadBase>();
        }
    
        public Nullable<int> CustomerTypeCode { get; set; }
        public Nullable<System.Guid> StageId { get; set; }
        public Nullable<bool> DoNotPhone { get; set; }
        public string Name { get; set; }
        public Nullable<int> AccountRatingCode { get; set; }
        public Nullable<bool> DoNotBulkPostalMail { get; set; }
        public Nullable<System.DateTime> LastUsedInCampaign { get; set; }
        public string EMailAddress3 { get; set; }
        public string Telephone1 { get; set; }
        public Nullable<bool> DoNotPostalMail { get; set; }
        public Nullable<bool> CreditOnHold { get; set; }
        public Nullable<int> AccountClassificationCode { get; set; }
        public string Fax { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<bool> DoNotFax { get; set; }
        public Nullable<bool> FollowEmail { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string SIC { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<int> PaymentTermsCode { get; set; }
        public Nullable<System.Guid> MasterId { get; set; }
        public Nullable<bool> DoNotSendMM { get; set; }
        public Nullable<int> OwnershipCode { get; set; }
        public Nullable<int> PreferredContactMethodCode { get; set; }
        public string WebSiteURL { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> SLAInvokedId { get; set; }
        public System.Guid AccountId { get; set; }
        public Nullable<int> PreferredAppointmentDayCode { get; set; }
        public Nullable<int> PreferredAppointmentTimeCode { get; set; }
        public Nullable<decimal> Aging60 { get; set; }
        public Nullable<decimal> MarketCap { get; set; }
        public Nullable<int> AccountCategoryCode { get; set; }
        public string TimeSpentByMeOnEmailAndMeetings { get; set; }
        public byte[] VersionNumber { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Aging90 { get; set; }
        public Nullable<System.Guid> CreatedByExternalParty { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.Guid> SLAId { get; set; }
        public Nullable<int> BusinessTypeCode { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<int> CustomerSizeCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> IndustryCode { get; set; }
        public System.Guid OwnerId { get; set; }
        public string TickerSymbol { get; set; }
        public Nullable<int> SharesOutstanding { get; set; }
        public Nullable<bool> Merged { get; set; }
        public string StockExchange { get; set; }
        public Nullable<System.DateTime> LastOnHoldTime { get; set; }
        public Nullable<bool> DoNotBulkEMail { get; set; }
        public Nullable<bool> DoNotEMail { get; set; }
        public string TraversedPath { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public string PrimaryTwitterId { get; set; }
        public Nullable<int> OnHoldTime { get; set; }
        public string FtpSiteURL { get; set; }
        public string Telephone3 { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public int StateCode { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public Nullable<int> NumberOfEmployees { get; set; }
        public Nullable<System.Guid> ParentAccountId { get; set; }
        public Nullable<int> ShippingMethodCode { get; set; }
        public Nullable<int> TerritoryCode { get; set; }
        public string EMailAddress2 { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public string PrimarySatoriId { get; set; }
        public Nullable<System.Guid> ModifiedByExternalParty { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> PreferredSystemUserId { get; set; }
        public Nullable<bool> ParticipatesInWorkflow { get; set; }
        public string EMailAddress1 { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<bool> MarketingOnly { get; set; }
        public string Telephone2 { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<decimal> Aging30 { get; set; }
        public Nullable<System.Guid> EntityImageId { get; set; }
        public Nullable<System.Guid> PrimaryContactId { get; set; }
        public int OwnerIdType { get; set; }
        public Nullable<decimal> Aging30_Base { get; set; }
        public Nullable<decimal> Aging60_Base { get; set; }
        public Nullable<decimal> Aging90_Base { get; set; }
        public Nullable<decimal> MarketCap_Base { get; set; }
        public Nullable<decimal> CreditLimit_Base { get; set; }
        public Nullable<decimal> Revenue_Base { get; set; }
        public string YomiName { get; set; }
        public Nullable<System.Guid> OriginatingLeadId { get; set; }
        public Nullable<System.Guid> DefaultPriceLevelId { get; set; }
        public Nullable<System.Guid> PreferredEquipmentId { get; set; }
        public Nullable<System.Guid> PreferredServiceId { get; set; }
        public Nullable<System.Guid> TerritoryId { get; set; }
        public Nullable<int> OpenDeals { get; set; }
        public Nullable<System.DateTime> OpenDeals_Date { get; set; }
        public Nullable<int> OpenDeals_State { get; set; }
        public Nullable<decimal> OpenRevenue { get; set; }
        public Nullable<decimal> OpenRevenue_Base { get; set; }
        public Nullable<System.DateTime> OpenRevenue_Date { get; set; }
        public Nullable<int> OpenRevenue_State { get; set; }
        public Nullable<int> TeamsFollowed { get; set; }
        public Nullable<bool> new_genders { get; set; }
        public string new_map { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountBase> AccountBase1 { get; set; }
        public virtual AccountBase AccountBase2 { get; set; }
        public virtual LeadBase LeadBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountBase> AccountBase11 { get; set; }
        public virtual AccountBase AccountBase3 { get; set; }
        public virtual ContactBase ContactBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadBase> LeadBases { get; set; }
    }
}
