//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeadBase()
        {
            this.AccountBases = new HashSet<AccountBase>();
            this.ContactBases = new HashSet<ContactBase>();
            this.LeadBase1 = new HashSet<LeadBase>();
        }
    
        public System.Guid LeadId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public System.Guid OwnerId { get; set; }
        public int OwnerIdType { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public string FullName { get; set; }
        public Nullable<System.Guid> ProcessId { get; set; }
        public Nullable<System.Guid> StageId { get; set; }
        public string TraversedPath { get; set; }
        public Nullable<System.Guid> ParentAccountId { get; set; }
        public Nullable<System.Guid> ParentContactId { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> BudgetAmount_Base { get; set; }
        public Nullable<int> BudgetStatus { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> ConfirmInterest { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<bool> DecisionMaker { get; set; }
        public string Description { get; set; }
        public Nullable<bool> DoNotBulkEMail { get; set; }
        public Nullable<bool> DoNotEMail { get; set; }
        public Nullable<bool> DoNotFax { get; set; }
        public Nullable<bool> DoNotPhone { get; set; }
        public Nullable<bool> DoNotPostalMail { get; set; }
        public Nullable<bool> DoNotSendMM { get; set; }
        public string EMailAddress1 { get; set; }
        public string EMailAddress2 { get; set; }
        public string EMailAddress3 { get; set; }
        public Nullable<decimal> EstimatedAmount { get; set; }
        public Nullable<decimal> EstimatedAmount_Base { get; set; }
        public Nullable<System.DateTime> EstimatedCloseDate { get; set; }
        public Nullable<double> EstimatedValue { get; set; }
        public Nullable<bool> EvaluateFit { get; set; }
        public string Fax { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> IndustryCode { get; set; }
        public Nullable<int> InitialCommunication { get; set; }
        public Nullable<bool> IsAutoCreate { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public string JobTitle { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> LastUsedInCampaign { get; set; }
        public Nullable<int> LeadQualityCode { get; set; }
        public Nullable<int> LeadSourceCode { get; set; }
        public Nullable<System.Guid> MasterId { get; set; }
        public Nullable<bool> Merged { get; set; }
        public string MiddleName { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> Need { get; set; }
        public Nullable<int> NumberOfEmployees { get; set; }
        public string Pager { get; set; }
        public Nullable<bool> ParticipatesInWorkflow { get; set; }
        public Nullable<int> PreferredContactMethodCode { get; set; }
        public Nullable<int> PriorityCode { get; set; }
        public Nullable<int> PurchaseProcess { get; set; }
        public string QualificationComments { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public Nullable<decimal> Revenue_Base { get; set; }
        public Nullable<int> SalesStage { get; set; }
        public Nullable<int> SalesStageCode { get; set; }
        public string Salutation { get; set; }
        public Nullable<System.DateTime> ScheduleFollowUp_Prospect { get; set; }
        public Nullable<System.DateTime> ScheduleFollowUp_Qualify { get; set; }
        public string SIC { get; set; }
        public int StateCode { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string Subject { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public Nullable<int> PurchaseTimeFrame { get; set; }
        public string WebSiteUrl { get; set; }
        public Nullable<System.Guid> SLAId { get; set; }
        public Nullable<System.Guid> SLAInvokedId { get; set; }
        public Nullable<int> OnHoldTime { get; set; }
        public Nullable<System.DateTime> LastOnHoldTime { get; set; }
        public Nullable<bool> FollowEmail { get; set; }
        public string TimeSpentByMeOnEmailAndMeetings { get; set; }
        public Nullable<System.Guid> EntityImageId { get; set; }
        public string CustomerIdName { get; set; }
        public Nullable<int> CustomerIdType { get; set; }
        public string CustomerIdYomiName { get; set; }
        public string YomiCompanyName { get; set; }
        public string YomiFirstName { get; set; }
        public string YomiFullName { get; set; }
        public string YomiLastName { get; set; }
        public string YomiMiddleName { get; set; }
        public Nullable<System.Guid> CampaignId { get; set; }
        public Nullable<System.Guid> RelatedObjectId { get; set; }
        public Nullable<System.Guid> OriginatingCaseId { get; set; }
        public Nullable<System.Guid> QualifyingOpportunityId { get; set; }
        public Nullable<bool> msdyn_gdproptout { get; set; }
        public Nullable<int> TeamsFollowed { get; set; }
        public string BusinessCard { get; set; }
        public string BusinessCardAttributes { get; set; }
        public Nullable<bool> new_TwoOption { get; set; }
        public string new_multioptionset { get; set; }
        public Nullable<System.Guid> new_file { get; set; }
        public Nullable<double> new_floatnumber { get; set; }
        public Nullable<int> new_wholenumber { get; set; }
        public Nullable<decimal> new_decimalnumber { get; set; }
        public Nullable<int> new_gender { get; set; }
        public string new_map { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountBase> AccountBases { get; set; }
        public virtual AccountBase AccountBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactBase> ContactBases { get; set; }
        public virtual ContactBase ContactBase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeadBase> LeadBase1 { get; set; }
        public virtual LeadBase LeadBase2 { get; set; }
    }
}
