//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crm_MSCRMEntities1 : DbContext
    {
        public crm_MSCRMEntities1()
            : base("name=crm_MSCRMEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountBase> AccountBases { get; set; }
        public virtual DbSet<AnnotationBase> AnnotationBases { get; set; }
        public virtual DbSet<ContactBase> ContactBases { get; set; }
        public virtual DbSet<LeadBase> LeadBases { get; set; }
        public virtual DbSet<new_LunaTechSupportBase> new_LunaTechSupportBase { get; set; }
        public virtual DbSet<new_list_contact> new_list_contact { get; set; }
        public virtual DbSet<new_LunaTechSupport> new_LunaTechSupport { get; set; }
    }
}
