//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_LunaTechSupportBase
    {
        public System.Guid new_LunaTechSupportId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public System.Guid OwnerId { get; set; }
        public int OwnerIdType { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public int statecode { get; set; }
        public Nullable<int> statuscode { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public string new_name { get; set; }
        public string new_Descriptions { get; set; }
        public string new_MobilePhone { get; set; }
        public string new_Email { get; set; }
        public Nullable<int> new_PredictingTheTime { get; set; }
        public Nullable<bool> new_Confirmation { get; set; }
        public string new_TrackingCode { get; set; }
        public Nullable<int> new_TimeSpent { get; set; }
        public string new_SupportUser { get; set; }
        public string new_SupportUserEmail { get; set; }
        public Nullable<System.DateTime> new_EstimatedDeliveryDate { get; set; }
        public Nullable<System.Guid> processid { get; set; }
        public Nullable<System.Guid> stageid { get; set; }
        public string traversedpath { get; set; }
        public Nullable<int> new_Type { get; set; }
        public Nullable<bool> new_UpdateCheck { get; set; }
    }
}
