//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerService
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_list_contact
    {
        public System.Guid new_list_contactId { get; set; }
        public byte[] VersionNumber { get; set; }
        public System.Guid listid { get; set; }
        public System.Guid contactid { get; set; }
    }
}
