//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public System.Guid AttributeId { get; set; }
        public Nullable<System.Guid> AttributeTypeId { get; set; }
        public string Name { get; set; }
        public string PhysicalName { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<bool> IsNullable { get; set; }
        public string XmlAbbreviation { get; set; }
        public System.Guid EntityId { get; set; }
        public string DefaultValue { get; set; }
        public int ColumnNumber { get; set; }
        public Nullable<bool> ValidForUpdateAPI { get; set; }
        public string LogicalName { get; set; }
        public Nullable<bool> ValidForReadAPI { get; set; }
        public Nullable<bool> ValidForCreateAPI { get; set; }
        public Nullable<bool> VisibleToPlatform { get; set; }
        public Nullable<bool> IsPKAttribute { get; set; }
        public Nullable<bool> IsCustomField { get; set; }
        public bool IsLogical { get; set; }
        public Nullable<int> DisplayMask { get; set; }
        public Nullable<System.Guid> AttributeOf { get; set; }
        public int ReferencedEntityObjectTypeCode { get; set; }
        public Nullable<System.Guid> AggregateOf { get; set; }
        public bool IsSortAttribute { get; set; }
        public Nullable<byte> PrecisionValue { get; set; }
        public Nullable<byte> PrecisionSource { get; set; }
        public bool IsIdentity { get; set; }
        public bool IsReplicated { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<System.Guid> YomiOf { get; set; }
        public System.Guid AttributeRowId { get; set; }
        public Nullable<int> AppDefaultValue { get; set; }
        public string AttributeLogicalTypeId { get; set; }
        public bool Locked { get; set; }
        public string AttributeImeModeId { get; set; }
        public string AttributeRequiredLevelId { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
        public Nullable<int> Accuracy { get; set; }
        public Nullable<int> AccuracySource { get; set; }
        public string LookupStyle { get; set; }
        public Nullable<bool> LookupBrowse { get; set; }
        public string ImeMode { get; set; }
        public bool HasMultipleLabels { get; set; }
        public bool IsRowGuidAttribute { get; set; }
        public Nullable<bool> IsBaseCurrency { get; set; }
        public Nullable<System.Guid> CalculationOf { get; set; }
        public bool IsAuditEnabled { get; set; }
        public string UpgradeDefaultValue { get; set; }
        public Nullable<System.Guid> OptionSetId { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public Nullable<System.Guid> LinkedAttributeId { get; set; }
        public Nullable<System.Guid> InheritsFrom { get; set; }
        public bool IsStoredOnPrimaryTable { get; set; }
        public bool IsInheritanceTypeAttribute { get; set; }
        public string TableColumnName { get; set; }
        public bool IsUnmanagedAttribute { get; set; }
        public bool IsOneWayBooleanAttribute { get; set; }
        public bool IsCustomizable { get; set; }
        public bool IsRenameable { get; set; }
        public bool CanModifySearchSettings { get; set; }
        public bool CanModifyRequirementLevelSettings { get; set; }
        public bool CanBeSecuredForCreate { get; set; }
        public bool CanBeSecuredForRead { get; set; }
        public bool CanBeSecuredForUpdate { get; set; }
        public bool IsSecured { get; set; }
        public string DeprecatedVersion { get; set; }
        public bool IsManaged { get; set; }
        public string ManagedPropertyLogicalName { get; set; }
        public Nullable<int> ManagedPropertyParentComponentType { get; set; }
        public string ManagedPropertyParentAttributeName { get; set; }
        public bool CanModifyAdditionalSettings { get; set; }
        public Nullable<System.Guid> ValuesFromRelationshipAttribute { get; set; }
        public bool CanModifyAuditSettings { get; set; }
        public string IntroducedVersion { get; set; }
        public bool IsEncrypted { get; set; }
        public int SourceType { get; set; }
        public string FormulaDefinition { get; set; }
        public int SourceTypeMask { get; set; }
        public string AutoNumberFormat { get; set; }
        public Nullable<int> Behavior { get; set; }
        public Nullable<bool> CanModifyBehavior { get; set; }
        public bool CanModifyGlobalFilterSettings { get; set; }
        public bool CanModifyIsSortableSettings { get; set; }
        public Nullable<System.Guid> ParentEnumAttributeId { get; set; }
        public string ExternalName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsDataSourceSecret { get; set; }
        public bool IsGlobalFilterEnabled { get; set; }
        public bool IsSearchable { get; set; }
        public bool IsFilterable { get; set; }
        public bool IsRetrievable { get; set; }
        public bool IsFilterableSetBySystem { get; set; }
        public bool IsRetrievableSetBySystem { get; set; }
        public bool IsSortableEnabled { get; set; }
        public long RecordId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual AttributeType AttributeType { get; set; }
    }
}
