//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributePicklistValue
    {
        public System.Guid AttributePicklistValueId { get; set; }
        public System.Guid AttributePicklistValueRowId { get; set; }
        public int Value { get; set; }
        public Nullable<int> State_Status_Value { get; set; }
        public string InvariantName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public byte[] VersionNumber { get; set; }
        public System.Guid OptionSetId { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public bool IsManaged { get; set; }
        public string TransitionData { get; set; }
        public string ParentValues { get; set; }
        public string ExternalValue { get; set; }
        public string Color { get; set; }
    }
}
