//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityRelationshipRole
    {
        public System.Guid EntityRelationshipRoleId { get; set; }
        public System.Guid EntityRelationshipId { get; set; }
        public System.Guid EntityId { get; set; }
        public byte RelationshipRoleType { get; set; }
        public Nullable<byte> NavPaneDisplayOption { get; set; }
        public Nullable<byte> NavPaneArea { get; set; }
        public Nullable<int> NavPaneOrder { get; set; }
        public string NavPaneIcon { get; set; }
        public Nullable<bool> NavPaneOffline { get; set; }
        public string NavPaneQueryApi { get; set; }
        public string NavPaneViewId { get; set; }
        public Nullable<bool> NavPaneIsCustomizable { get; set; }
        public System.Guid EntityRelationshipRoleRowId { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<System.Guid> IntersectEntityAttributeId { get; set; }
        public Nullable<int> AssociationRoleOrdinal { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public string NavPaneId { get; set; }
        public bool IsManaged { get; set; }
        public string LogicalName { get; set; }
        public string NavigationPropertyName { get; set; }
        public long RecordId { get; set; }
    }
}
