//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityKey
    {
        public System.Guid EntityKeyId { get; set; }
        public System.Guid EntityId { get; set; }
        public System.Guid EntityKeyRowId { get; set; }
        public byte ComponentState { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public string Name { get; set; }
        public string LogicalName { get; set; }
        public System.Guid IndexId { get; set; }
        public string IntroducedVersion { get; set; }
        public Nullable<bool> IsCustomizable { get; set; }
        public bool IsManaged { get; set; }
        public int EntityKeyIndexStatus { get; set; }
        public System.Guid AsyncJobId { get; set; }
        public byte[] VersionNumber { get; set; }
        public bool IsExportKey { get; set; }
        public bool IsSynchronous { get; set; }
    }
}
