//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public System.Guid EntityId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ObjectTypeCode { get; set; }
        public string PhysicalName { get; set; }
        public string LogicalName { get; set; }
        public string CollectionName { get; set; }
        public string BaseTableName { get; set; }
        public string LogicalCollectionName { get; set; }
        public bool IsIntersect { get; set; }
        public bool IsSecurityIntersect { get; set; }
        public bool IsLookupTable { get; set; }
        public int EventMask { get; set; }
        public Nullable<bool> IsLogicalEntity { get; set; }
        public Nullable<bool> IsCustomizable { get; set; }
        public Nullable<bool> IsCollaboration { get; set; }
        public Nullable<bool> IsActivity { get; set; }
        public string AddressTableName { get; set; }
        public Nullable<bool> IsMappable { get; set; }
        public int OwnershipTypeMask { get; set; }
        public bool IsAudited { get; set; }
        public bool UsesFullnameConventionRules { get; set; }
        public bool IsParented { get; set; }
        public Nullable<int> EntityMask { get; set; }
        public bool IsReplicated { get; set; }
        public bool IsReplicationUserFiltered { get; set; }
        public bool IsChildEntity { get; set; }
        public bool IsCustomEntity { get; set; }
        public bool IsActivityParty { get; set; }
        public bool IsValidForAdvancedFind { get; set; }
        public string ExtensionTableName { get; set; }
        public byte[] VersionNumber { get; set; }
        public string ReportViewName { get; set; }
        public bool IsRequiredOffline { get; set; }
        public bool IsRenameable { get; set; }
        public string EntityClassName { get; set; }
        public string ServiceClassName { get; set; }
        public string EntityAssembly { get; set; }
        public string ServiceAssembly { get; set; }
        public System.Guid EntityRowId { get; set; }
        public bool IsDuplicateCheckSupported { get; set; }
        public bool IsImportable { get; set; }
        public bool IsShareableAcrossOrgs { get; set; }
        public bool IsPublishable { get; set; }
        public string OriginalLocalizedName { get; set; }
        public string OriginalLocalizedCollectionName { get; set; }
        public bool CanTriggerWorkflow { get; set; }
        public int WorkflowSupport { get; set; }
        public bool CanBeChildInCustomRelationship { get; set; }
        public bool CanBeInCustomEntityAssociation { get; set; }
        public bool CanBeInCustomReflexiveRelationship { get; set; }
        public bool IsMailMergeEnabled { get; set; }
        public int RecurrenceTypeMask { get; set; }
        public Nullable<System.Guid> RecurrenceBaseEntityId { get; set; }
        public bool IsDocumentManagementEnabled { get; set; }
        public int MobileAccessLevelMask { get; set; }
        public bool IsVisibleInMobile { get; set; }
        public bool IsMultipleQueueEnabled { get; set; }
        public bool AutoRouteToOwnerQueue { get; set; }
        public bool IsAuditEnabled { get; set; }
        public bool IsConnectionsEnabled { get; set; }
        public bool IsReadingPaneEnabled { get; set; }
        public bool IsMapiGridEnabled { get; set; }
        public bool IsEnabledForCharts { get; set; }
        public string IconLargeName { get; set; }
        public string IconMediumName { get; set; }
        public string IconSmallName { get; set; }
        public int NextCustomAttributeColumnNumber { get; set; }
        public int ActivityTypeMask { get; set; }
        public bool IsSolutionAware { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public Nullable<System.Guid> InheritsFrom { get; set; }
        public bool IsInheritedFrom { get; set; }
        public bool CanBeSecured { get; set; }
        public bool CanModifyConnectionSettings { get; set; }
        public bool CanModifyDuplicateDetectionSettings { get; set; }
        public bool CanModifyMailMergeSettings { get; set; }
        public bool CanModifyQueueSettings { get; set; }
        public bool CanCreateAttributes { get; set; }
        public bool CanBeRelatedEntityInRelationship { get; set; }
        public bool CanBePrimaryEntityInRelationship { get; set; }
        public bool CanBeInManyToMany { get; set; }
        public bool CanCreateForms { get; set; }
        public bool CanCreateCharts { get; set; }
        public bool CanCreateViews { get; set; }
        public bool CanModifyAuditSettings { get; set; }
        public bool CanModifyMobileVisibility { get; set; }
        public Nullable<int> ParentComponentType { get; set; }
        public string ParentControllingAttributeName { get; set; }
        public bool IsManaged { get; set; }
        public bool CanModifyAdditionalSettings { get; set; }
        public bool IsAIRUpdated { get; set; }
        public bool IsQuickCreateEnabled { get; set; }
        public string IntroducedVersion { get; set; }
        public bool AutoCreateAccessTeams { get; set; }
        public bool IsBusinessProcessEnabled { get; set; }
        public bool HasIdsTable { get; set; }
        public bool IsReadOnlyInMobileClient { get; set; }
        public bool IsVisibleInMobileClient { get; set; }
        public bool CanModifyMobileClientVisibility { get; set; }
        public bool CanModifyMobileClientReadOnly { get; set; }
        public bool IsEnabledForTrace { get; set; }
        public bool CanChangeHierarchicalRelationship { get; set; }
        public string EntityHelpUrl { get; set; }
        public bool EntityHelpUrlEnabled { get; set; }
        public bool IsHSMEnabled { get; set; }
        public bool UsesBusinessDataLabelTable { get; set; }
        public bool IsStateModelAware { get; set; }
        public bool EnforceStateTransitions { get; set; }
        public bool ChangeTrackingEnabled { get; set; }
        public bool CanChangeTrackingBeEnabled { get; set; }
        public bool CanEnableSyncToExternalSearchIndex { get; set; }
        public bool SyncToExternalSearchIndex { get; set; }
        public Nullable<System.Guid> DataProviderId { get; set; }
        public Nullable<System.Guid> DataSourceId { get; set; }
        public int EntityClass { get; set; }
        public string EntityColor { get; set; }
        public string EntitySetName { get; set; }
        public string ExternalCollectionName { get; set; }
        public string ExternalName { get; set; }
        public string IconVectorName { get; set; }
        public bool IsInteractionCentricEnabled { get; set; }
        public bool IsBPFEntity { get; set; }
        public bool IsDocumentRecommendationsEnabled { get; set; }
        public bool IsMergeEnabledSolutionComponent { get; set; }
        public bool IsOneNoteIntegrationEnabled { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsSLAEnabled { get; set; }
        public string MobileOfflineFilters { get; set; }
        public bool IsOfflineInMobileClient { get; set; }
        public bool CanModifyMobileClientOffline { get; set; }
        public int DaysSinceRecordLastModified { get; set; }
        public bool IsEnabledForExternalChannels { get; set; }
        public bool CanExternalChannelsBeEnabled { get; set; }
        public bool IsOptimisticConcurrencyRequired { get; set; }
        public bool IsOptimisticConcurrencyEnabled { get; set; }
        public bool CanOptimisticConcurrencyBeEnabled { get; set; }
        public bool CanOptimisticConcurrencyBeRequired { get; set; }
        public int AvailableForRetrieve { get; set; }
        public int AvailableForRetrieveMultiple { get; set; }
        public int AvailableForCreate { get; set; }
        public int AvailableForUpdate { get; set; }
        public int AvailableForDelete { get; set; }
        public bool IsKnowledgeManagementEnabled { get; set; }
        public bool IsRetrieveAuditEnabled { get; set; }
        public bool IsRetrieveMultipleAuditEnabled { get; set; }
        public bool IsMSTeamsIntegrationEnabled { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string SettingOf { get; set; }
    }
}
