//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityIndex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityIndex()
        {
            this.IndexAttributes = new HashSet<IndexAttribute>();
            this.IndexFilters = new HashSet<IndexFilter>();
        }
    
        public System.Guid IndexId { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> EntityId { get; set; }
        public Nullable<bool> IsClustered { get; set; }
        public Nullable<bool> IsUnique { get; set; }
        public Nullable<int> SqlFillFactor { get; set; }
        public Nullable<bool> RecreateIndex { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> IndexType { get; set; }
        public Nullable<bool> IsPrimaryKey { get; set; }
        public bool IsUniqueConstraint { get; set; }
        public int State { get; set; }
        public Nullable<System.Guid> KeyIndexAttributeId { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public byte ComponentState { get; set; }
        public string CompressionType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndexAttribute> IndexAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndexFilter> IndexFilters { get; set; }
    }
}
