//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityRelationship
    {
        public System.Guid EntityRelationshipId { get; set; }
        public string SchemaName { get; set; }
        public byte EntityRelationshipType { get; set; }
        public bool IsCustomRelationship { get; set; }
        public System.Guid EntityRelationshipRowId { get; set; }
        public byte[] VersionNumber { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public bool IsCustomizable { get; set; }
        public bool IsManaged { get; set; }
        public string IntroducedVersion { get; set; }
        public bool CanChangeHierarchicalSettings { get; set; }
        public bool IsHierarchical { get; set; }
        public long RecordId { get; set; }
    }
}
