//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FailedIndexCreation
    {
        public System.Guid IndexId { get; set; }
        public Nullable<int> NumberOfAttempts { get; set; }
        public Nullable<System.DateTime> LastAttemptTime { get; set; }
    }
}
