//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentKnowledgeBaseRecord
    {
        public System.Guid IncidentKnowledgeBaseRecordId { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public string Name { get; set; }
        public System.Guid IncidentId { get; set; }
        public System.Guid KnowledgeBaseRecordId { get; set; }
    
        public virtual IncidentBase IncidentBase { get; set; }
    }
}
