//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexAttribute
    {
        public System.Guid IndexAttributeId { get; set; }
        public Nullable<System.Guid> AttributeId { get; set; }
        public Nullable<System.Guid> IndexId { get; set; }
        public Nullable<int> IndexOrder { get; set; }
        public bool IsIncludeAttribute { get; set; }
        public bool SortDescending { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public int State { get; set; }
        public bool IsSystemManaged { get; set; }
        public bool IsQuickFindManaged { get; set; }
    
        public virtual EntityIndex EntityIndex { get; set; }
    }
}
