//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexFilter
    {
        public System.Guid IndexFilterId { get; set; }
        public System.Guid IndexId { get; set; }
        public System.Guid AttributeId { get; set; }
        public string FilterOperator { get; set; }
        public string FilterValue { get; set; }
    
        public virtual EntityIndex EntityIndex { get; set; }
    }
}
