//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocalizedLabel_BAK
    {
        public System.Guid LocalizedLabelId { get; set; }
        public System.Guid LocalizedLabelRowId { get; set; }
        public int LanguageId { get; set; }
        public System.Guid ObjectId { get; set; }
        public string ObjectColumnName { get; set; }
        public string Label { get; set; }
        public byte[] VersionNumber { get; set; }
        public int LabelTypeCode { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public bool IsManaged { get; set; }
    }
}
