//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagedProperty
    {
        public System.Guid ManagedPropertyId { get; set; }
        public System.Guid ManagedPropertyRowId { get; set; }
        public string LogicalName { get; set; }
        public int ManagedPropertyType { get; set; }
        public Nullable<int> Operation { get; set; }
        public bool IsGlobalForOperation { get; set; }
        public int EvaluationPriority { get; set; }
        public bool IsPrivate { get; set; }
        public bool DefaultValue { get; set; }
        public Nullable<int> ErrorCode { get; set; }
        public Nullable<bool> EnablesMetadata { get; set; }
        public string EnablesEntityName { get; set; }
        public string EnablesAttributeName { get; set; }
        public string EvaluationConditionClass { get; set; }
        public string EvaluationConditionAssembly { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public bool IsManaged { get; set; }
        public byte[] VersionNumber { get; set; }
        public string IntroducedVersion { get; set; }
    }
}
