//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LunaGroup_MSCRMEntities : DbContext
    {
        public LunaGroup_MSCRMEntities()
            : base("name=LunaGroup_MSCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountBase> AccountBases { get; set; }
        public virtual DbSet<AnnotationBase> AnnotationBases { get; set; }
        public virtual DbSet<ContactBase> ContactBases { get; set; }
        public virtual DbSet<IncidentBase> IncidentBases { get; set; }
        public virtual DbSet<IncidentKnowledgeBaseRecord> IncidentKnowledgeBaseRecords { get; set; }
        public virtual DbSet<IncidentResolutionBase> IncidentResolutionBases { get; set; }
        public virtual DbSet<LeadBase> LeadBases { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<AttributeLookupValue> AttributeLookupValues { get; set; }
        public virtual DbSet<AttributePicklistValue> AttributePicklistValues { get; set; }
        public virtual DbSet<AttributeType> AttributeTypes { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<EntityIndex> EntityIndexes { get; set; }
        public virtual DbSet<EntityKey> EntityKeys { get; set; }
        public virtual DbSet<EntityKeyAttribute> EntityKeyAttributes { get; set; }
        public virtual DbSet<EntityRelationship> EntityRelationships { get; set; }
        public virtual DbSet<EntityRelationshipRelationship> EntityRelationshipRelationships { get; set; }
        public virtual DbSet<EntityRelationshipRole> EntityRelationshipRoles { get; set; }
        public virtual DbSet<IndexAttribute> IndexAttributes { get; set; }
        public virtual DbSet<IndexFilter> IndexFilters { get; set; }
        public virtual DbSet<LocalizedLabel> LocalizedLabels { get; set; }
        public virtual DbSet<ManagedProperty> ManagedProperties { get; set; }
        public virtual DbSet<OptionSet> OptionSets { get; set; }
        public virtual DbSet<Relationship> Relationships { get; set; }
        public virtual DbSet<RelationshipExtraCondition> RelationshipExtraConditions { get; set; }
        public virtual DbSet<StoredProcedureCatalog> StoredProcedureCatalogs { get; set; }
        public virtual DbSet<ViewAttribute> ViewAttributes { get; set; }
        public virtual DbSet<FailedIndexCreation> FailedIndexCreations { get; set; }
        public virtual DbSet<FailedRelationshipCreation> FailedRelationshipCreations { get; set; }
        public virtual DbSet<LocalizedLabel_BAK> LocalizedLabel_BAK { get; set; }
        public virtual DbSet<OrganizationLanguagePack> OrganizationLanguagePacks { get; set; }
    }
}
