//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public string CreatedOnString { get; set; }
        public System.Guid NotificationId { get; set; }
        public int NotificationNumber { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string EventData { get; set; }
        public System.Guid OrganizationId { get; set; }
        public int EventId { get; set; }
    }
}
