//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionSet
    {
        public System.Guid OptionSetId { get; set; }
        public System.Guid OptionSetRowId { get; set; }
        public string Name { get; set; }
        public byte OptionSetType { get; set; }
        public bool IsGlobal { get; set; }
        public bool IsCustomOptionSet { get; set; }
        public byte[] VersionNumber { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public bool IsCustomizable { get; set; }
        public bool IsManaged { get; set; }
        public string IntroducedVersion { get; set; }
        public Nullable<System.Guid> ParentOptionSetId { get; set; }
        public string ExternalTypeName { get; set; }
    }
}
