//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationLanguagePack
    {
        public System.Guid OrganizationId { get; set; }
        public int LanguageId { get; set; }
        public bool IsEnabled { get; set; }
        public string Version { get; set; }
        public bool LabelCacheSharingEnabled { get; set; }
    }
}
