//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationshipExtraCondition
    {
        public System.Guid ConditionId { get; set; }
        public System.Guid RelationshipId { get; set; }
        public System.Guid AttributeId { get; set; }
        public byte ConditionOp { get; set; }
        public int Value { get; set; }
        public System.Guid RelationshipExtraConditionRowId { get; set; }
        public byte[] VersionNumber { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public bool IsManaged { get; set; }
    }
}
