//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public System.Guid RelationshipId { get; set; }
        public string Name { get; set; }
        public System.Guid ReferencingEntityId { get; set; }
        public System.Guid ReferencingAttributeId { get; set; }
        public System.Guid ReferencedEntityId { get; set; }
        public System.Guid ReferencedAttributeId { get; set; }
        public Nullable<int> RelationshipType { get; set; }
        public bool IsLogical { get; set; }
        public byte CascadeDelete { get; set; }
        public Nullable<byte> CascadeAssign { get; set; }
        public Nullable<byte> CascadeShare { get; set; }
        public Nullable<byte> CascadeUnShare { get; set; }
        public Nullable<byte> CascadeMerge { get; set; }
        public Nullable<byte> CascadeReparent { get; set; }
        public Nullable<long> CascadeLinkMask { get; set; }
        public bool IsCustomRelationship { get; set; }
        public bool IsValidForAdvancedFind { get; set; }
        public byte[] VersionNumber { get; set; }
        public System.Guid RelationshipRowId { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public bool IsManaged { get; set; }
        public string IntroducedVersion { get; set; }
        public Nullable<byte> CascadeRollupView { get; set; }
        public long RecordId { get; set; }
        public Nullable<System.Guid> EntityKeyId { get; set; }
    }
}
