//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoredProcedureCatalog
    {
        public System.Guid StoredProcedureId { get; set; }
        public string Name { get; set; }
        public string DatabaseName { get; set; }
        public Nullable<int> TargetMask { get; set; }
        public string Description { get; set; }
        public int InstallationSequence { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public byte ComponentState { get; set; }
        public string Content { get; set; }
    }
}
