//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewAttribute
    {
        public System.Guid ViewAttributeId { get; set; }
        public System.Guid AttributeId { get; set; }
        public System.Guid RelationshipId { get; set; }
        public System.Guid RemoteAttributeId { get; set; }
        public byte[] VersionNumber { get; set; }
        public System.Guid ViewAttributeRowId { get; set; }
        public bool IsDenormalized { get; set; }
        public System.Guid SolutionId { get; set; }
        public System.Guid SupportingSolutionId { get; set; }
        public byte ComponentState { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public bool IsManaged { get; set; }
    }
}
